name: github pages

on:
  push:
    branches:
      - master
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@master
        with:
          version: '3.x'

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - run: go mod tidy
      - run: go install
          github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
          github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
          github.com/golang/protobuf/protoc-gen-go

      - run: go generate
        env:
          GOPATH: $HOME/go

      - name: Deploy source
        uses: peaceiris/actions-gh-pages@v3.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: test
          publish_dir: .

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          RUNNER_TEMP: "abc"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install -g redoc-cli

      - name: Build docs
        run: redoc-cli bundle ./src/api.swagger.json

      - run: mkdir -p ./public && mv redoc-static.html ./public/index.html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
